version: 2

# ── Build environment ──
build:
  # Which Ubuntu image to use
  os: ubuntu-22.04
  # Which Python to install
  tools:
    python: "3.10"

# ── Python installation ──
python:
  install:
    # Install your package so mkdocstrings can import it
    - method: pip
      path: .
    # Install any MkDocs‐related dependencies
    - requirements: docs/requirements.txt

# ── MkDocs config ──
mkdocs:
  # Point to your mkdocs config
  configuration: mkdocs.yml
