tasks:
  - name: fetch_page1
    task: call_api
    rate_limit: 2            # no more than 2 calls/sec
    rate_limit_key: "api"
    params:
      url: "https://example.com/page1"

  - name: fetch_page2
    task: call_api
    rate_limit: 2            # shared with fetch_page1
    rate_limit_key: "api"
    params:
      url: "https://example.com/page2"

  - name: aggregate
    task: aggregate_results
    depends_on:
      - fetch_page1
      - fetch_page2
